# SPDX-FileCopyrightText: 2024 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "Twelve"
SPDX-PackageSupplier = "The LineageOS Project"
SPDX-PackageDownloadLocation = "https://github.com/LineageOS/android_packages_apps_Twelve"

[[annotations]]
path = [".github/workflows/**", ".gitignore", "app/.gitignore", "app/schemas/org.lineageos.twelve.database.TwelveDatabase/*.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 The LineageOS Project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gradle/wrapper/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2007-2023 Gradle, Inc."
SPDX-License-Identifier = "Apache-2.0"
